version: "3.6"

services:
  nextcloud:
    image: nextcloud
    env_file: /home/docker/nextcloud/NC_setup/config/nextcloud.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data

  db:
    image: mariadb:10
    env_file: /home/docker/nextcloud/NC_setup/config/nextcloud.env
    volumes:
      - database:/var/lib/mysql

  db-backup:
    image: mariadb:10
    env_file: /home/docker/nextcloud/NC_setup/config/nextcloud-db-backup.env
    volumes:
      - database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  solr:
    image: solr:6-alpine
    volumes:
    - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant

  cron:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done
        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'

volumes:
  nextcloud:
    driver: cloudstor:aws
  apps:
    driver: cloudstor:aws
  config:
    driver: cloudstor:aws
  data:
    driver: cloudstor:aws
  database:
    driver: cloudstor:aws
  database-dump:
    driver: cloudstor:aws
  redis:
    driver: cloudstor:aws
  solr:
    driver: cloudstor:aws
